name: sample_feature_flag
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  device_info_plus: ^3.1.0
  firebase_analytics: ^8.3.3
  firebase_core: ^1.7.0
  firebase_remote_config: ^0.11.0+1
  flutter_scale_tap: ^1.0.5
  get_it: ^7.1.3
  package_info_plus: ^1.3.0
  provider: ^6.0.1
  pub_semver: ^2.1.0
  twemoji: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#FFD740"
  adaptive_icon_foreground: "assets/app_icon.png"
